spring.application.name=lottery_system

logging.config=classpath:logback-spring.xml
spring.profiles.active=dev
## MySql ##
#é©±å¨ç±»åç§°
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#æ°æ®åºurl
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/lottery_system?characterEncoding=utf8&useSSL=false
#ç¨æ·å
spring.datasource.username=root
#å¯ç 
spring.datasource.password=root
## MyBatis ##
#Mapper.xmlæä»¶è·¯å¾
#mybatis.mapper-locations=classpath:mapper/*Mapper.xml
#è®¾ç½®é©¼å³°èªå¨è½¬æ¢
mybatis.configuration.map-underscore-to-camel-case=true
#è®¾ç½®ç±»åå¤çå¨
mybatis.type-handlers-package=org.example.lottery_system.dao.handler
#ç­ä¿¡éç½®
sms.access-key-id=LTAI5tEkLSTLhgdVrxFX6czpNew-Item .gitignore -ItemType File -Value "application.properties"
sms.access-key-secret=gRmxmpHYpMLrLZar7WGb8UvF9uQ9Y7
## redis ##
spring.data.redis.host=localhost
spring.data.redis.port=8888
# è¿æ¥ç©ºé²è¶è¿N(sç§ãmsæ¯«ç§)åå³é­ï¼0ä¸ºç¦ç¨ï¼è¿ééç½®å¼åtcp-keepaliveå¼ä¸è´
spring.data.redis.timeout=60s
# é»è®¤ä½¿ç¨ lettuce è¿æ¥æ± 
# åè®¸æå¤§è¿æ¥æ°ï¼é»è®¤8ï¼è´å¼è¡¨ç¤ºæ²¡æéå¶ï¼
spring.data.redis.lettuce.pool.max-active=8
# æå¤§ç©ºé²è¿æ¥æ°ï¼é»è®¤8
spring.data.redis.lettuce.pool.max-idle=8
# æå°ç©ºé²è¿æ¥æ°ï¼é»è®¤0
spring.data.redis.lettuce.pool.min-idle=0
# è¿æ¥ç¨å®æ¶ï¼æ°çè¯·æ±ç­å¾æ¶é´(sç§ãmsæ¯«ç§)ï¼è¶è¿è¯¥æ¶é´æåºå¼å¸¸JedisConnectionExceptionï¼(é»è®¤-1ï¼è´å¼è¡¨ç¤ºæ²¡æéå¶)
spring.data.redis.lettuce.pool.max-wait=5s
## å¾çæå¡ ##
pic.local-path=D:/PIC
# spring boot3 åçº§éç½®å
spring.web.resources.static-locations=classpath:/static/,file:${pic.local-path}
## mq ##
spring.rabbitmq.host=8.136.222.102
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
#æ¶æ¯ç¡®è®¤æºå¶ï¼é»è®¤auto
spring.rabbitmq.listener.simple.acknowledge-mode=auto
#è®¾ç½®å¤±è´¥éè¯ 5æ¬¡
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=5
# Spring QQé®ç®± Configuration
spring.mail.host=smtp.qq.com
spring.mail.port=465
spring.mail.username=2746993199@qq.com
spring.mail.password=bpjsmdtomnztdeca
spring.mail.protocol=smtps
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.required=true
## çº¿ç¨æ±  ##
async.executor.thread.core_pool_size=10
async.executor.thread.max_pool_size=20
async.executor.thread.queue_capacity=20
async.executor.thread.name.prefix=async-service
## ç­ä¿¡å®ç¸å³éç½® ##
smsbao.username=caiyudong
smsbao.api-key=9569bcfbdbee4e6184e540b784e63b09
smsbao.signature=ãæ½å¥ç³»ç»ã
smsbao.api-url=http://api.smsbao.com/sms